version: "3"
services:
  web:
   build: 
    context: .
    dockerfile: Dockerfile.dev
   ports:
    - "3000:3000"
   volumes:
    - /aplikacija/node_modules
    - .:/aplikacija 
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
        - /aplikacija/node_modules
        - .:/aplikacija
    command: ["npm", "run", "test"]    